name: git-release
on:
  workflow_call:
    secrets:
      github-token:
        required: true
    outputs:
      semver:
        value: ${{ jobs.release.outputs.semver }}
        description: semver from our release branch name

# TODO: Replace the marvinpinto action with: https://github.com/marvinpinto/action-automatic-releases/pull/2#issuecomment-1817530497
jobs:
  release:
    name: "Extract semver from release branch"
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.semver.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract semver from release branch name
        shell: bash
        id: semver
        env:
          MESSAGE: "${{ github.event.head_commit.message }}"
        run: |
          echo "value=$(./scripts/gittag.sh)" >> $GITHUB_OUTPUT
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.github-token }}"
          automatic_release_tag: "${{ steps.semver.outputs.value }}"
          prerelease: false
          draft: false
          title: "${{ steps.semver.outputs.value }}"
